services:
  db:
    image: postgres:13-alpine
    container_name: my_postgres_db
    environment:
      # Cú pháp ${BIEN_O_FILE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  crawler:
    build: ./app
    container_name: my_python_crawler
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1  # <--- THÊM DÒNG NÀY
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - ./app:/app
volumes:
  pg_data: