name: Deploy to AWS ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Lấy code từ kho về
      uses: actions/checkout@v3

    - name: 2. Đăng nhập vào AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1  # Server Singapore (Nếu bạn dùng Mỹ thì đổi thành us-east-1)

    - name: 3. Đăng nhập vào ECR (Nhà kho)
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 4. Đóng gói và Đẩy hàng đi
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tiki-crawler  # Tên kho bạn tạo lúc nãy
        IMAGE_TAG: latest
      run: |
        # Build Docker Image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Đẩy lên AWS
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
